### ISSUE TITLE
Oncoprint with only one gene

### ISSUE THREAD

**Issue by msquatrito** [jokergoo/ComplexHeatmap#19]
Hi, 
First of all, great package!
I've been playing a little bit with the `oncoPrint` function and I've realized that is not possible to plot data from one single gene.I've no problem in plotting multiple genes. However, when I try with a matrix containing info for one gene only, I get the following error message:

Error in apply(count_matrix[row_order, ], 2, scoreCol) : 
  dim(X) must have a positive length

I guess it's due to the fact that the matrix that I'm passing to oncoPrint contains only one row. Do you know any work around for it? 
Thanks
Massimo

**Comment by jokergoo** [comment]
I forgot to add `drop = FALSE` when subsetting the matrix. Now it is fixed and you can install the new version from GitHub

**Comment by msquatrito** [comment]
I've installed the GitHub version but I'm still getting an error message:

`
Error in .local(object, ...) : 
  Number of rows in the matrix are not the same as the length of
the cluster or the row orders.
`

**Comment by jokergoo** [comment]
Sorry it is because the dimension of matrix is not correctly set in some other part in the code. I just updated the package and I hope this issue is fixed. Also I have tested it with one gene matrix as well as one sample matrix.

**Comment by msquatrito** [comment]
This issue is now fixed.
Thanks!
