### ISSUE TITLE
Cannot install ComplexHeatmap from github

### ISSUE THREAD

**Issue by semmrich** [jokergoo/ComplexHeatmap#583]
Hi Zuguang,
First off let me congratulate you for developing an amazing visualization tool, and special Kudo's for the excellent maintenance efforts!
Using your reference book @ [https://jokergoo.github.io/ComplexHeatmap-reference/book/] i was trying to get the most updated version, as the one from Bioc is below 2.5.1 (installing that version 2.4.3 works actually).
I tried your template
`library(devtools)
install_github("jokergoo/ComplexHeatmap")`
and got this:
```
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo jokergoo/ComplexHeatmap@HEAD
Skipping 2 packages ahead of CRAN: colorspace, png
√  checking for file 'C:\Users\fuchsdeluxe\AppData\Local\Temp\Rtmpiy6ufN\remotes24d026773d88\jokergoo-ComplexHeatmap-21f5aa8/DESCRIPTION' (377ms)
-  preparing 'ComplexHeatmap': (1.4s)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (1.4s)
-  checking for empty or unneeded directories
-  building 'ComplexHeatmap_2.5.5.tar.gz'
   
Error: Failed to install 'ComplexHeatmap' from GitHub:
  (converted from warning) installation of package ‘C:/Users/FUCHSD~1/AppData/Local/Temp/Rtmpiy6ufN/file24d0499b2eef/ComplexHeatmap_2.5.5.tar.gz’ had non-zero exit status
```

```
Session info ------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.2 (2020-06-22)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/New_York            
 date     2020-09-11                  

- Packages ----------------------------------------------------------------------------------------------------------------------------------------------
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.0)
 backports     1.1.9   2020-08-24 [1] CRAN (R 4.0.2)
 callr         3.4.4   2020-09-07 [1] CRAN (R 4.0.2)
 cli           2.0.2   2020-02-28 [1] CRAN (R 4.0.0)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 4.0.0)
 curl          4.3     2019-12-02 [1] CRAN (R 4.0.0)
 desc          1.2.0   2018-05-01 [1] CRAN (R 4.0.0)
 devtools    * 2.3.1   2020-07-21 [1] CRAN (R 4.0.2)
 digest        0.6.25  2020-02-23 [1] CRAN (R 4.0.0)
 ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.0)
 fansi         0.4.1   2020-01-08 [1] CRAN (R 4.0.0)
 fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.2)
 glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.2)
 magrittr      1.5     2014-11-22 [1] CRAN (R 4.0.2)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 4.0.0)
 pkgbuild      1.1.0   2020-07-13 [1] CRAN (R 4.0.2)
 pkgload       1.1.0   2020-05-29 [1] CRAN (R 4.0.0)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.0)
 processx      3.4.4   2020-09-03 [1] CRAN (R 4.0.2)
 ps            1.3.4   2020-08-11 [1] CRAN (R 4.0.2)
 R6            2.4.1   2019-11-12 [1] CRAN (R 4.0.0)
 remotes       2.2.0   2020-07-21 [1] CRAN (R 4.0.2)
 rlang         0.4.7   2020-07-09 [1] CRAN (R 4.0.2)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 4.0.0)
 rstudioapi    0.11    2020-02-07 [1] CRAN (R 4.0.0)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.0)
 testthat      2.3.2   2020-03-02 [1] CRAN (R 4.0.0)
 usethis     * 1.6.1   2020-04-29 [1] CRAN (R 4.0.0)
 withr         2.2.0   2020-04-20 [1] CRAN (R 4.0.0)

[1] C:/Program Files/R/R-4.0.2/library
```

I am running RStudio in admin mode under Win10 with enough disk space for this package.
Also I set
`.libPaths("C:/Program Files/R/R-4.0.2/library")`

Any help is highly appreciated!

Thanks in advance,
Stephan

**Comment by jokergoo** [comment]
How about now?

I made some changes and the package didn't pass R CMD check. Now I have fixed it.

**Comment by semmrich** [comment]
weird, the error persists...

```
> .libPaths("C:/Program Files/R/R-4.0.2/library")
> library(devtools)
Loading required package: usethis
> install_github("jokergoo/ComplexHeatmap")
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo jokergoo/ComplexHeatmap@HEAD
Skipping 2 packages ahead of CRAN: colorspace, png
√  checking for file 'C:\Users\fuchsdeluxe\AppData\Local\Temp\Rtmpk9zXjk\remotes3f3c59ec68a6\jokergoo-ComplexHeatmap-485e4d1/DESCRIPTION' (389ms)
-  preparing 'ComplexHeatmap': (1.5s)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (1.5s)
-  checking for empty or unneeded directories
-  building 'ComplexHeatmap_2.5.5.tar.gz'
   
Error: Failed to install 'ComplexHeatmap' from GitHub:
  (converted from warning) installation of package ‘C:/Users/FUCHSD~1/AppData/Local/Temp/Rtmpk9zXjk/file3f3c5a8f2872/ComplexHeatmap_2.5.5.tar.gz’ had non-zero exit status
```

I explicitely open RStudio as admin...
The same error occurs when I use the R GUI x64 in admin mode...
This computer is not part of a secured network, and in admin mode I can install any packages so far, CRAN or github, doesn't matter.
It seems it is related to my device though, very unfortunate.

I want to use ComplexHeatmap to visualize voom-transformed limma results of RNA-Seq for a number of hematopoietic stem and progenitor bulk populations, using datasets from 6 different publications. Pheatmap row clustering however distorts the order of how DEGs for each "group" or celltype (columns) are displayed (Seurat for scRNA-Seq data display is my aim here, see
[https://satijalab.org/seurat/v3.2/pbmc3k_tutorial.html](url)
`DoHeatmap(pbmc, features = top10$gene) + NoLegend()`
(at the bottom page of the vignette)
Thus I need to instruct a tool with a list of cols and rows preordered to depict the DEGs per group, and from your manual I think ComplexHeatmap can do that plus gives many more options to adjust parameters than pheatmap of heatmap.2
Do you think the BIOC version 2.4.3 is what I should go for then, or should I keep trying to run the most recent 2.5.5?

Thank You again for your help and time,
Stephan

**Comment by jokergoo** [comment]
I don't know why you cannot install this package. Permission? I cannot see the error message for the fail.

Anyway, I think you can just use an older version. Just pick one that you can install.

And how about directly install the zip from http://bioconductor.org/packages/devel/bioc/html/ComplexHeatmap.html?

**Comment by semmrich** [comment]
Yay, That worked! Probably bc 
`BiocManager::install(version='devel')`
did update BIOC on my R, thus installing 2.5.5 instead of the older 2.4.3.
Thank You Sir! Problem solved 🥇
